version: '3'
services:
  wallet:
    restart: always
    container_name: "wallet"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/usr/app/core"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/home/wallet/media:/media"
    command: uvicorn app.main:app --reload --loop asyncio --host 0.0.0.0:8000
    env_file:
      - .env
    networks:
      - public
    ports:
      - "0.0.0.0:8001:8000"

  wallet-mongo:
    restart: always
    container_name: "wallet-mongo"
    image: "$MONGO_IMAGE"
    volumes:
      - '../database:/data/db'
    networks:
      - public
    ports:
      - "127.0.0.1:27018:27017"

  wallet-redis:
    restart: always
    container_name: "wallet-redis"
    image: "redis"
    networks:
      - public

  nginx:
    image: nginx:1.19.7
    user: root
    restart: always
    container_name: "nginx"
    volumes:
      - /home/wallet/wallet/nginx_conf/default.conf:/etc/nginx/conf.d/default.conf
      - /home/wallet/wallet/nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - /home/wallet/media:/media
    ports:
      - "80:80/tcp"

networks:
  public:
    external: true